# Generated by Django 2.1.7 on 2019-03-20 14:09

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atitle', models.CharField(max_length=32, verbose_name='文章标题')),
                ('acontent', DjangoUeditor.models.UEditorField(blank=True, verbose_name='文章内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='article_images/%Y/%m%d', verbose_name='文章图片')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='文章阅读量')),
                ('add_datatime', models.DateTimeField(auto_now_add=True, verbose_name='文章添加时间')),
                ('update_datatime', models.DateTimeField(auto_now=True, verbose_name='文章更新时间')),
            ],
            options={
                'verbose_name': '博客文章',
                'verbose_name_plural': '博客文章',
            },
        ),
        migrations.CreateModel(
            name='Bloguser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=16, verbose_name='用户名称')),
                ('uemail', models.EmailField(max_length=254, verbose_name='用户邮箱')),
                ('uphone', models.CharField(max_length=11, verbose_name='用户手机号')),
                ('upassword', models.CharField(max_length=16, verbose_name='用户密码')),
                ('uavatar', models.ImageField(blank=True, null=True, upload_to='avatar_images/%Y/%m%d', verbose_name='用户头像')),
                ('join_datatime', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('last_login_datatime', models.DateTimeField(auto_now=True, verbose_name='最后登录时间')),
            ],
            options={
                'verbose_name': '博客用户',
                'verbose_name_plural': '博客用户',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=16, verbose_name='分类名称')),
                ('corder', models.IntegerField(default=0, verbose_name='分类排序')),
            ],
            options={
                'verbose_name': '博客分类',
                'verbose_name_plural': '博客分类',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=16, verbose_name='链接名称')),
                ('lurl', models.URLField(max_length=128, verbose_name='链接地址')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=16, verbose_name='标签名称')),
            ],
            options={
                'verbose_name': '博客标签',
                'verbose_name_plural': '博客标签',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='acategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='文章分类'),
        ),
        migrations.AddField(
            model_name='article',
            name='atag',
            field=models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='文章标签'),
        ),
        migrations.AddField(
            model_name='article',
            name='auser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Bloguser', verbose_name='文章作者'),
        ),
    ]
