# Generated by Django 2.1.7 on 2019-03-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='uemail',
            field=models.EmailField(max_length=254, null=True, verbose_name='用户邮箱'),
        ),
    ]
